[build-system]
requires = [
    "setuptools>=65.4.1",
    "scikit-build>=0.15.0",
    "cmake>=3.10.0",
    "ninja",
    "wheel",
    "cython",
    "numpy<1.22",
]
build-backend = "setuptools.build_meta"
